In [4]:
import numpy as np

A = np.array([
             [ 56.0, 0.0, 4.4, 68.8],
             [ 1.2,  104, 52.0, 8.0],
             [ 1.8, 135.0, 99.0, 0.9]
            ])
print(A)

[[ 56.    0.    4.4  68.8]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [6]:
calorie = A.sum(axis=0) #if 0 = sum vertically, if 1 = sum horizontally
print(calorie)

[ 59.  239.  155.4  77.7]


In [13]:
percentage = 100*A/calorie.reshape(1,4) #broadcasting
print(percentage)

[[94.91525424  0.          2.83140283 88.54568855]
 [ 2.03389831 43.51464435 33.46203346 10.2960103 ]
 [ 3.05084746 56.48535565 63.70656371  1.15830116]]


ValueError: cannot reshape array of size 12 into shape (3,1)

In [32]:
a = np.random.randn(32, 32)
print(a)

a.reshape((32*32,1))

[[-0.73705994 -0.86175852  1.51855555 ...  0.66530426  0.24944723
   0.2481205 ]
 [ 0.92929463 -0.21220494 -0.14748403 ...  1.00794111 -0.47544262
  -1.03659408]
 [ 1.26782139  0.26963699 -0.34875241 ... -0.3534621   0.9880746
   0.34695863]
 ...
 [-0.40596305  0.24288671  0.74168366 ...  1.34943766  0.48244392
   0.42361656]
 [-0.37447676  0.52605987  0.50302012 ... -1.28717317  0.37133621
   0.23678792]
 [-1.06286456  0.56537287 -1.18701739 ...  1.56521966  0.64689943
  -0.34359727]]


array([[-0.73705994],
       [-0.86175852],
       [ 1.51855555],
       ...,
       [ 1.56521966],
       [ 0.64689943],
       [-0.34359727]])

In [12]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("vectorized version: " + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()


print(c)
print("non-vectorized version: " + str(1000*(toc-tic)) + "ms")

250107.30476334467
vectorized version: 1.1959075927734375ms
250107.30476333655
non-vectorized version: 925.750732421875ms


In [20]:
u = np.zeros((5,1))
u

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])